services:
  # Node.js Service
  - type: web
    name: piewallah
    env: node
    rootDir: .
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18
